### PR TITLE
Make minimap usable for navigation & show indenting

### PR DESCRIPTION
**Pull request by mipmip**
Includes pull request from cybertim (fixed autocmd, added toggle, fixed map focus)

### CODE REVIEW

**Comment by hbetts** [comment]
:+1: These changes would be really helpful.

**Comment by severin-lemaignan** [comment]
Merged your changes, thank you! (...5 months of lag... beautiful...)

**Comment by mipmip** [comment]
:+1: Thanks anyway

**Comment by hbetts** [comment]
Thanks @severin-lemaignan!

**Pull request merged**
