### PR TITLE
Don't redraw the whole file every time

### PR DESCRIPTION
**Pull request by dpc**
I quite arbitrarily picked +/- 80 lines, as potentially visible context.

### CODE REVIEW

**Comment by dpc** [comment]
That alone makes this plugin almost usable. I'm looking into other speed easy-picks.

**Comment by severin-lemaignan** [comment]
Excellent! Thanks!

**Comment by jamesdbowman** [comment]
Can we configure this value in our ~/.vimrc?

**Comment by dpc** [comment]
It's definitely doable. Please submit a PR. I might get to it at some point too.

**Pull request merged**
